### ISSUE TITLE
doesnt't work

### ISSUE THREAD

**Issue by astrocyted** [dlrudco/Fast-Audioset-Download#5] opened 2024-02-08 13:19 UTC
it doesnt download anything at all. I mean i see activity in the temp folder, files and folders being created and deleted, and the progress bar moving forward but zero with end substance, not a single audio file downloaded despite the full engagement of all my cpu power and fans.

**Comment by dlrudco** [comment] 2024-02-08 14:07
Hi! Sorry to hear that my code isn't working properly. Recently, I have been notified by someone else for similar reason, and thus updated my code. Can you check again if you are using the latest commit of this repo? See if the code is using yt_dlp instead of old youtube-dl.

I have tested again within my ubuntu setup, and verified it works as expected. If you are using the latest version and still experiencing this issue, please let me know some more details so that I can reproduce the problem.

**Comment by dlrudco** [comment] 2024-02-08 14:17
Oops I also noticed that the extension was set to 'mp3' instead of 'm4a' in the recent commit. I don't know why. Please change the extension to 'm4a' and try again.

**Comment by astrocyted** [comment] 2024-02-08 14:38
thanks for the quick reply. I just cloned the repo last night, so it was the latest version. turned out the issue was indeed the 'mp3' extension. issue resolved. thanks.

**Comment by dlrudco** [comment] 2024-02-08 14:52
Nice to hear that! closing issue

**Closed as completed by dlrudco** 2024-02-08 14:52 UTC

**Comment by SaraAlthubaiti** [comment] 2024-12-31 16:36
@dlrudco I'm having the same exact issue and when I debug the code using:

`import traceback` and this print statement `print(traceback.format_exc())` in this section:

```
        except Exception as e:
            print(traceback.format_exc())
            os.system(f'rm -rf temps/id_{ids}')
            return f'{url} - ytdl : {log_stream.getvalue()}, system : {str(e)}'
    return None
```
It seems the issue of not founding `audio.mp3` because the YouTube file not downloaded:

```
Traceback (most recent call last):
  File "/opt/conda/envs/ptca/lib/python3.8/shutil.py", line 791, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: 'temps/id_-0DQ1Fv8Ej4/audio.mp3' -> 'wavs/unbalanced_train/000000/id_-0DQ1Fv8Ej4.mp3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/Fast-Audioset-Download/download.py", line 121, in download_audio
    shutil.move(os.path.join(f'temps/id_{ids}',f'audio.{ext}'), os.path.join(outpath, filename))
  File "/opt/conda/envs/ptca/lib/python3.8/shutil.py", line 811, in move
    copy_function(src, real_dst)
  File "/opt/conda/envs/ptca/lib/python3.8/shutil.py", line 435, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/opt/conda/envs/ptca/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'temps/id_-0DQ1Fv8Ej4/audio.mp3'
```
And it keeps showing this for each YouTube id. Could you please guide me on how to make it running successfully?
Thanks.
